version: "3.7"
services:
  mongo_db:
    image: mongo:4
    container_name: "mongo_db"
    command: mongod
    ports:
      - "27017:27017"
    env_file:
      - .env
    networks:
      - samplenetwork

  mongo_seed:
    container_name: mongo_seed
    build: ./mongo_seed
    links:
      - mongo_db
    networks:
      - samplenetwork

  node_app:
    depends_on:
      - mongo_db
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app/
      - ./nodemon.json:/home/node/app/nodemon.json
    networks:
      - samplenetwork
networks:
  samplenetwork:
    driver: bridge
