version: "3.7"
services:
  mongodb:
    image: mongo:4
    container_name: "mongodb"
    command: mongod
    ports:
      - "27017:27017"
    env_file:
      - .env

  node_app:
    depends_on:
      - mongodb
    build: .
    command: bash -c 'while !</dev/tcp/db/3306; do sleep 1; done; npm start'
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/app/
      - ./nodemon.json:/home/node/app/nodemon.json
